version: '3.8'

name: "singq"

volumes:
  ncanode_cache:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_signq
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=signq_db
      - JWT_SECRET_KEY=b5ebd2e57d95932a503d8b6475130c11716fd25bed5dfef4839544da34cda50f
    ports:
      - "8080:8080"

  db:
    image: postgres:11.7
    container_name: db_signq
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=signq_db
    ports:
      - "5433:5432"

  nca_node:
    image: malikzh/ncanode
    ports:
      - "14579:14579"
    volumes:
      - ncanode_cache:/app/cache